language: c

env:
  - LIB="C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\um\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64"

script:
  - mkdir build && cd build && cmake .. && cmake --build .

matrix:
  include:
    - os: windows
      compiler: clang
    - os: osx
      osx_image: xcode10.3
      compiler: clang
    - os: linux
      compiler: gcc
